// =============================================================================
// ultraenv — .env.example Generator
// Reads .env files and produces safe .env.example files with stripped secrets,
// type hints, descriptions, and required/optional markers.
// =============================================================================

import type { ParsedEnvVar, SchemaDefinition } from '../core/types.js';
import { parseEnvFile } from '../core/parser.js';
import { readFile, writeFile, exists } from '../utils/fs.js';
import { isSecretKey, isSecretLike, maskValue } from '../utils/mask.js';

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

export interface GenerateExampleOptions {
  /** Include type hint comments (default: true) */
  includeDescriptions?: boolean;
  /** Include type annotation comments (default: true) */
  includeTypes?: boolean;
  /** Include default values in comments (default: true) */
  includeDefaults?: boolean;
  /** Path to a schema file (TypeScript module exporting schema) for metadata */
  schemaPath?: string;
}

interface ExampleLine {
  /** The text content of the line (may be comment or variable) */
  content: string;
  /** The original line number for ordering */
  order: number;
}

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

const HEADER = [
  '# ============================================================',
  '# Auto-generated by ultraenv — DO NOT EDIT',
  '# Copy this file to .env and fill in the values',
  '# ============================================================',
  '',
].join('\n');

// -----------------------------------------------------------------------------
// Schema Type Mapping
// -----------------------------------------------------------------------------

type SchemaEntry = SchemaDefinition[string];

/** Map schema type to a human-readable comment string */
function schemaTypeToString(schema: SchemaEntry): string {
  const schemaRecord = schema as unknown as Record<string, unknown>;
  if ('type' in schemaRecord) {
    const schemaType = schemaRecord.type as string;
    switch (schemaType) {
      case 'string': return 'string';
      case 'number': return 'number';
      case 'boolean': return 'boolean';
      case 'enum': return 'enum';
      case 'array': return 'array (comma-separated)';
      case 'json': return 'json';
      case 'date': return 'date (ISO 8601)';
      case 'bigint': return 'bigint';
      default: return 'string';
    }
  }
  return 'string';
}

/** Extract enum values from an enum schema for display */
function extractEnumValues(schema: SchemaEntry): string[] | null {
  const schemaRecord = schema as unknown as Record<string, unknown>;
  if (schemaRecord.type === 'enum') {
    const values = schemaRecord.values;
    if (values !== undefined && Array.isArray(values)) {
      return [...(values as readonly string[])];
    }
  }
  if (schemaRecord.type === 'string') {
    const enumValues = schemaRecord.enum;
    if (enumValues !== undefined && Array.isArray(enumValues)) {
      return [...(enumValues as readonly string[])];
    }
  }
  return null;
}

// -----------------------------------------------------------------------------
// Secret Detection
// -----------------------------------------------------------------------------

/**
 * Determine if a variable should be treated as a secret based on
 * schema metadata, key name heuristics, and value patterns.
 */
function isSecretVariable(key: string, value: string, schema?: SchemaEntry): boolean {
  // Check schema metadata for secret marker
  if (schema !== undefined) {
    const schemaRecord = schema as unknown as Record<string, unknown>;
    if (schemaRecord.isSecret === true) {
      return true;
    }
  }
  // Check key name heuristics
  if (isSecretKey(key)) {
    return true;
  }
  // Check value pattern heuristics (only for non-empty values)
  if (value.length > 0 && isSecretLike(value)) {
    return true;
  }
  return false;
}

// -----------------------------------------------------------------------------
// Public API
// -----------------------------------------------------------------------------

/**
 * Generate a .env.example file from a .env file.
 *
 * Reads the .env file, strips secret values, preserves comments and variable
 * ordering, and optionally adds type hints, descriptions, and default values
 * from a schema definition.
 *
 * @param envPath - Path to the source .env file
 * @param outputPath - Path where the .env.example will be written
 * @param options - Generation options
 * @throws FileSystemError if the .env file cannot be read
 */
export async function generateExampleFile(
  envPath: string,
  outputPath: string,
  options?: GenerateExampleOptions,
): Promise<void> {
  const includeDescriptions = options?.includeDescriptions ?? true;
  const includeTypes = options?.includeTypes ?? true;
  const includeDefaults = options?.includeDefaults ?? true;

  const content = await readFile(envPath);
  const schema = options?.schemaPath !== undefined
    ? await loadSchema(options.schemaPath)
    : undefined;

  const parsed = parseEnvFile(content, envPath);
  const generated = generateExampleContent(parsed.vars, schema, {
    includeDescriptions,
    includeTypes,
    includeDefaults,
  });

  await writeFile(outputPath, generated);
}

/**
 * Generate the content of a .env.example file from parsed variables.
 *
 * @param vars - Parsed environment variables from a .env file
 * @param schema - Optional schema definition for type/description metadata
 * @param options - Generation options
 * @returns The complete .env.example file content as a string
 */
export function generateExampleContent(
  vars: readonly ParsedEnvVar[],
  schema?: SchemaDefinition,
  options?: {
    includeDescriptions?: boolean;
    includeTypes?: boolean;
    includeDefaults?: boolean;
  },
): string {
  const includeDescriptions = options?.includeDescriptions ?? true;
  const includeTypes = options?.includeTypes ?? true;
  const includeDefaults = options?.includeDefaults ?? true;

  const lines: ExampleLine[] = [];
  let order = 0;

  // Track which variables have been emitted (to avoid duplicates)
  const emittedKeys = new Set<string>();

  // Add header
  lines.push({ content: HEADER, order: order++ });

  for (const envVar of vars) {
    if (emittedKeys.has(envVar.key)) continue;
    emittedKeys.add(envVar.key);

    const schemaEntry = schema !== undefined ? schema[envVar.key] : undefined;
    const schemaRecord = schemaEntry !== undefined ? schemaEntry as unknown as Record<string, unknown> : undefined;
    const isRequired = schemaEntry === undefined || schemaEntry.optional !== true;
    const isSecret = isSecretVariable(envVar.key, envVar.value, schemaEntry);

    // Build comment block above the variable
    const commentLines: string[] = [];

    // Description comment
    if (includeDescriptions && schemaEntry?.description !== undefined) {
      commentLines.push(`# ${schemaEntry.description}`);
    }

    // Type hint comment
    if (includeTypes && schemaEntry !== undefined) {
      const typeStr = schemaTypeToString(schemaEntry);
      commentLines.push(`# type: ${typeStr}`);

      // Enum values
      const enumValues = extractEnumValues(schemaEntry);
      if (enumValues !== null) {
        commentLines.push(`# values: ${enumValues.join(', ')}`);
      }
    }

    // Secret marker
    if (isSecret) {
      commentLines.push('# [SECRET]');
    }

    // Required/optional marker
    if (includeDescriptions) {
      if (isRequired && schemaRecord?.default === undefined) {
        commentLines.push('# required');
      } else if (schemaRecord?.default !== undefined) {
        commentLines.push('# optional');
      } else if (schemaEntry?.optional === true) {
        commentLines.push('# optional');
      }
    }

    // Default value
    if (includeDefaults) {
      if (schemaRecord?.default !== undefined) {
        const defaultDisplay = isSecret
          ? '[REDACTED]'
          : String(schemaRecord.default);
        commentLines.push(`# default: ${defaultDisplay}`);
      } else if (schemaRecord?.hasDefault === true && typeof schemaRecord.rawDefaultValue === 'string') {
        const defaultDisplay = isSecret
          ? '[REDACTED]'
          : schemaRecord.rawDefaultValue;
        commentLines.push(`# default: ${defaultDisplay}`);
      }
    }

    // Push comment lines
    for (const commentLine of commentLines) {
      lines.push({ content: commentLine, order: order++ });
    }

    // Push the variable line with stripped value
    const exampleValue = buildExampleValue(envVar.value, isSecret, schemaEntry);
    lines.push({
      content: `${envVar.key}=${exampleValue}`,
      order: order++,
    });

    // Add blank line between variables
    lines.push({ content: '', order: order++ });
  }

  // Sort by original order and build final content
  lines.sort((a, b) => a.order - b.order);
  return lines.map((line) => line.content).join('\n');
}

// -----------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------

/**
 * Build the example value for a variable.
 * Secrets are replaced with a placeholder, other values get a generic example.
 */
function buildExampleValue(
  value: string,
  isSecret: boolean,
  schema?: SchemaEntry,
): string {
  if (isSecret) {
    // For secrets, provide a generic placeholder
    return '<your-secret-here>';
  }

  // Check for enum — show first option
  if (schema !== undefined) {
    const enumValues = extractEnumValues(schema);
    if (enumValues !== null && enumValues.length > 0) {
      return enumValues[0] ?? '';
    }
  }

  // Empty value — leave it empty
  if (value === '') {
    return '';
  }

  // For non-secret values, provide a masked placeholder that preserves format hints
  if (value.length <= 20 && !isSecretLike(value)) {
    // Short non-secret values could be safe to show as-is for documentation
    // but we mask them anyway for safety
    return maskValue(value, { visibleStart: 0, visibleEnd: 0, minLength: 1 });
  }

  return maskValue(value, { visibleStart: 0, visibleEnd: 0, minLength: 1 });
}

/**
 * Load a schema definition from a TypeScript module path.
 * Since we can't execute TypeScript at runtime, this attempts to read
 * a JSON schema definition or returns undefined.
 */
async function loadSchema(_schemaPath: string): Promise<SchemaDefinition | undefined> {
  // Schema loading from TypeScript files requires compilation.
  // In production, schemas are passed directly from the application code.
  // This function is a placeholder for future JSON schema support.
  void _schemaPath;
  return undefined;
}

/**
 * Check if a .env.example file needs updating by comparing its content
 * with what would be generated from the current .env file.
 */
export async function needsUpdate(
  envPath: string,
  examplePath: string,
  options?: GenerateExampleOptions,
): Promise<boolean> {
  const envExists = await exists(envPath);
  const exampleExists = await exists(examplePath);

  // If env exists but example doesn't, update is needed
  if (envExists && !exampleExists) {
    return true;
  }

  // If neither exists, no update needed
  if (!envExists) {
    return false;
  }

  const content = await readFile(envPath);
  const schema = options?.schemaPath !== undefined
    ? await loadSchema(options.schemaPath)
    : undefined;

  const parsed = parseEnvFile(content, envPath);
  const generated = generateExampleContent(parsed.vars, schema, {
    includeDescriptions: options?.includeDescriptions ?? true,
    includeTypes: options?.includeTypes ?? true,
    includeDefaults: options?.includeDefaults ?? true,
  });

  const existing = await readFile(examplePath);
  return generated.trim() !== existing.trim();
}
