// =============================================================================
// ultraenv — Environment Creator
// Creates new .env.{name} files from templates, existing environments, or
// interactively with prompts.
// =============================================================================

import { resolve, join } from 'node:path';
import type { SchemaDefinition } from '../core/types.js';
import { readFile, writeFile, exists, removeFile } from '../utils/fs.js';
import { parseEnvFile } from '../core/parser.js';
import { FileSystemError } from '../core/errors.js';

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

export interface CreateEnvironmentOptions {
  copyFrom?: string;
  fromTemplate?: string;
  interactive?: boolean;
  schema?: SchemaDefinition;
  cwd?: string;
  values?: Record<string, string>;
}

interface VariableDefinition {
  key: string;
  value: string;
  description?: string;
  isSecret: boolean;
  isRequired: boolean;
  hasDefault: boolean;
  defaultValue?: string;
  type: string;
}

// -----------------------------------------------------------------------------
// Built-in Templates
// -----------------------------------------------------------------------------

const NODEJS_TEMPLATE = `# Node.js Backend Environment
# Created by ultraenv

# Server
PORT=3000
HOST=localhost
NODE_ENV=development

# Database
DATABASE_URL=
DATABASE_POOL_SIZE=10

# Authentication
JWT_SECRET=
JWT_EXPIRES_IN=7d

# CORS
ALLOWED_ORIGINS=http://localhost:3000

# Logging
LOG_LEVEL=info
LOG_FORMAT=json

# Feature Flags
DEBUG=false
VERBOSE=false
`;

const NEXTJS_TEMPLATE = `# Next.js Frontend Environment
# Created by ultraenv

# Framework
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://localhost:3001

# Analytics
NEXT_PUBLIC_GA_ID=
NEXT_PUBLIC_SENTRY_DSN=

# Feature Flags
NEXT_PUBLIC_DEBUG=false
NEXT_PUBLIC_MAINTENANCE=false
`;

const DOCKER_TEMPLATE = `# Docker Deployment Environment
# Created by ultraenv

# Container
CONTAINER_PORT=3000
HOST_PORT=3000

# Database
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USER=
POSTGRES_PASSWORD=
POSTGRES_DB=

# Redis
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=

# Networking
NETWORK_NAME=app-network
`;

const BUILTIN_TEMPLATES: ReadonlyMap<string, string> = new Map<string, string>([
  ['nodejs', NODEJS_TEMPLATE],
  ['nextjs', NEXTJS_TEMPLATE],
  ['docker', DOCKER_TEMPLATE],
]);

// -----------------------------------------------------------------------------
// Variable Extraction
// -----------------------------------------------------------------------------

function extractVariables(content: string, schema?: SchemaDefinition): VariableDefinition[] {
  const parsed = parseEnvFile(content);
  const variables: VariableDefinition[] = [];
  const seenKeys = new Set<string>();

  if (schema !== undefined) {
    for (const [key, schemaEntry] of Object.entries(schema)) {
      if (seenKeys.has(key)) continue;
      seenKeys.add(key);

      const r = schemaEntry as unknown as Record<string, unknown>;
      variables.push({
        key,
        value: '',
        description: schemaEntry.description,
        isSecret: r.isSecret === true,
        isRequired:
          schemaEntry.optional !== true &&
          schemaEntry.default === undefined &&
          r.hasDefault !== true,
        hasDefault: schemaEntry.default !== undefined || r.hasDefault === true,
        defaultValue: typeof r.rawDefaultValue === 'string' ? r.rawDefaultValue : undefined,
        type: typeof r.typeName === 'string' ? r.typeName : 'string',
      });
    }
  }

  for (const envVar of parsed.vars) {
    if (seenKeys.has(envVar.key)) continue;
    seenKeys.add(envVar.key);

    variables.push({
      key: envVar.key,
      value: envVar.value,
      isSecret: false,
      isRequired: false,
      hasDefault: false,
      type: 'string',
    });
  }

  return variables;
}

// -----------------------------------------------------------------------------
// Content Generation
// -----------------------------------------------------------------------------

function generateEnvironmentContent(
  variables: VariableDefinition[],
  values: Record<string, string>,
): string {
  const lines: string[] = [];

  lines.push(`# Environment: generated by ultraenv`);
  lines.push(`# Created: ${new Date().toISOString()}`);
  lines.push('');

  for (const variable of variables) {
    if (variable.description !== undefined) {
      lines.push(`# ${variable.description}`);
    }

    lines.push(`# type: ${variable.type}`);

    if (variable.isRequired) {
      lines.push('# required');
    } else if (variable.hasDefault && variable.defaultValue !== undefined) {
      lines.push(`# default: ${variable.defaultValue}`);
    } else {
      lines.push('# optional');
    }

    if (variable.isSecret) {
      lines.push('# [SECRET]');
    }

    const providedValue = values[variable.key];
    if (providedValue !== undefined) {
      lines.push(`${variable.key}=${providedValue}`);
    } else if (variable.hasDefault && variable.defaultValue !== undefined) {
      lines.push(`${variable.key}=${variable.defaultValue}`);
    } else if (variable.isSecret) {
      lines.push(`${variable.key}=`);
    } else if (variable.isRequired) {
      lines.push(`${variable.key}=`);
    } else {
      lines.push(`# ${variable.key}=`);
    }

    lines.push('');
  }

  return lines.join('\n');
}

function collectValues(
  variables: VariableDefinition[],
  providedValues?: Record<string, string>,
): Record<string, string> {
  const values: Record<string, string> = { ...providedValues };

  for (const variable of variables) {
    if (variable.key in values) continue;
    if (!variable.isRequired && !variable.hasDefault) continue;

    if (variable.hasDefault && variable.defaultValue !== undefined) {
      values[variable.key] = variable.defaultValue;
    }
  }

  return values;
}

// -----------------------------------------------------------------------------
// Name Validation
// -----------------------------------------------------------------------------

function validateEnvironmentName(name: string): void {
  if (name.length === 0) {
    throw new FileSystemError('Environment name cannot be empty', {
      path: '',
      operation: 'validate',
      hint: 'Provide a valid environment name (e.g., "staging", "production").',
    });
  }

  if (name.length > 64) {
    throw new FileSystemError(`Environment name too long: ${name.length} characters (max 64)`, {
      path: '',
      operation: 'validate',
      hint: 'Use a shorter environment name.',
    });
  }

  if (!/^[a-zA-Z0-9_-]+$/.test(name)) {
    throw new FileSystemError(
      `Invalid environment name: "${name}". Only alphanumeric characters, hyphens, and underscores are allowed.`,
      {
        path: '',
        operation: 'validate',
        hint: 'Use names like "staging", "production", "ci", "dev-v2", etc.',
      },
    );
  }

  const reserved = ['local', 'example', 'template', 'bak', 'backup', 'old', 'tmp', 'temp'];
  if (reserved.includes(name.toLowerCase())) {
    throw new FileSystemError(`Reserved environment name: "${name}"`, {
      path: '',
      operation: 'validate',
      hint: `The name "${name}" is reserved. Choose a different name.`,
    });
  }
}

// -----------------------------------------------------------------------------
// Public API
// -----------------------------------------------------------------------------

export async function createEnvironment(
  name: string,
  options?: CreateEnvironmentOptions,
): Promise<void> {
  validateEnvironmentName(name);

  const baseDir = resolve(options?.cwd ?? process.cwd());
  const outputPath = join(baseDir, `.env.${name}`);

  if (await exists(outputPath)) {
    throw new FileSystemError(`Environment file already exists: ".env.${name}"`, {
      path: outputPath,
      operation: 'create',
      hint: 'Delete the existing file first, or use a different environment name.',
    });
  }

  let content: string;
  let variables: VariableDefinition[] = [];

  if (options?.copyFrom !== undefined) {
    const sourcePath = join(baseDir, `.env.${options.copyFrom}`);
    if (!(await exists(sourcePath))) {
      throw new FileSystemError(`Source environment not found: ".env.${options.copyFrom}"`, {
        path: sourcePath,
        operation: 'read',
        hint: `Ensure ".env.${options.copyFrom}" exists before copying.`,
      });
    }
    content = await readFile(sourcePath);
    variables = extractVariables(content, options?.schema);

    const sourceParsed = parseEnvFile(content, sourcePath);
    const sourceValues: Record<string, string> = {};
    for (const envVar of sourceParsed.vars) {
      sourceValues[envVar.key] = envVar.value;
    }
    content = generateEnvironmentContent(variables, {
      ...sourceValues,
      ...options?.values,
    });
  } else if (options?.fromTemplate !== undefined) {
    const templatePath = resolve(options.fromTemplate);
    const builtinTemplate = BUILTIN_TEMPLATES.get(options.fromTemplate.toLowerCase());
    if (builtinTemplate !== undefined) {
      content = builtinTemplate;
    } else if (await exists(templatePath)) {
      content = await readFile(templatePath);
    } else {
      throw new FileSystemError(`Template not found: "${options.fromTemplate}"`, {
        path: templatePath,
        operation: 'read',
        hint: 'Use a built-in template name (nodejs, nextjs, docker) or a valid file path.',
      });
    }
    variables = extractVariables(content, options?.schema);
    const values = collectValues(variables, options?.values);
    content = generateEnvironmentContent(variables, values);
  } else if (options?.schema !== undefined) {
    const schemaVars: VariableDefinition[] = [];
    for (const [key, schemaEntry] of Object.entries(options.schema)) {
      const r = schemaEntry as unknown as Record<string, unknown>;
      schemaVars.push({
        key,
        value: '',
        description: schemaEntry.description,
        isSecret: r.isSecret === true,
        isRequired:
          schemaEntry.optional !== true &&
          schemaEntry.default === undefined &&
          r.hasDefault !== true,
        hasDefault: schemaEntry.default !== undefined || r.hasDefault === true,
        defaultValue: typeof r.rawDefaultValue === 'string' ? r.rawDefaultValue : undefined,
        type: typeof r.typeName === 'string' ? r.typeName : 'string',
      });
    }
    const values = collectValues(schemaVars, options?.values);
    content = generateEnvironmentContent(schemaVars, values);
  } else {
    content = [
      `# Environment: ${name}`,
      `# Created by ultraenv on ${new Date().toISOString()}`,
      '',
      '# Add your environment variables here',
      '',
    ].join('\n');
  }

  await writeFile(outputPath, content);
}

export function listTemplates(): ReadonlyArray<{ name: string; description: string }> {
  return [
    {
      name: 'nodejs',
      description: 'Node.js backend environment (PORT, DATABASE_URL, JWT, CORS, etc.)',
    },
    {
      name: 'nextjs',
      description: 'Next.js frontend environment (NEXT_PUBLIC_* variables, analytics, etc.)',
    },
    {
      name: 'docker',
      description: 'Docker deployment environment (container ports, Postgres, Redis, etc.)',
    },
  ];
}

export async function removeEnvironment(name: string, cwd?: string): Promise<void> {
  const baseDir = resolve(cwd ?? process.cwd());
  const filePath = join(baseDir, `.env.${name}`);

  if (!(await exists(filePath))) {
    throw new FileSystemError(`Environment file not found: ".env.${name}"`, {
      path: filePath,
      operation: 'unlink',
      hint: 'The environment does not exist.',
    });
  }

  await removeFile(filePath);
}

export async function duplicateEnvironment(
  sourceName: string,
  targetName: string,
  cwd?: string,
): Promise<void> {
  await createEnvironment(targetName, {
    copyFrom: sourceName,
    cwd,
  });
}
