import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import {
  generateExampleContent,
  generateExampleFile,
  needsUpdate,
} from '../../../src/sync/generator.js';
import type { ParsedEnvVar } from '../../../src/core/types.js';

// Mock the fs utilities
vi.mock('../../../src/utils/fs.js', () => ({
  readFile: vi.fn(),
  writeFile: vi.fn(),
  exists: vi.fn(),
}));

vi.mock('../../../src/core/parser.js', () => ({
  parseEnvFile: vi.fn(),
}));

import { readFile, writeFile, exists } from '../../../src/utils/fs.js';
import { parseEnvFile } from '../../../src/core/parser.js';

const mockReadFile = vi.mocked(readFile);
const mockWriteFile = vi.mocked(writeFile);
const mockExists = vi.mocked(exists);
const mockParseEnvFile = vi.mocked(parseEnvFile);

describe('sync generator', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  // ===========================================================================
  // generateExampleContent
  // ===========================================================================
  describe('generateExampleContent', () => {
    function makeVar(key: string, value: string): ParsedEnvVar {
      return {
        key,
        value,
        raw: value,
        source: '.env',
        lineNumber: 1,
        comment: '',
      };
    }

    it('generates content with header', () => {
      const vars = [makeVar('DATABASE_URL', 'postgres://localhost/db')];
      const content = generateExampleContent(vars);
      expect(content).toContain('Auto-generated by ultraenv');
      expect(content).toContain('Copy this file to .env');
    });

    it('replaces secret values with placeholder', () => {
      const vars = [makeVar('SECRET_KEY', 'sk-abcdefghijklmnopqrstuvwxyz012345')];
      const content = generateExampleContent(vars);
      expect(content).toContain('SECRET_KEY=<your-secret-here>');
    });

    it('adds [SECRET] marker for secret variables', () => {
      const vars = [makeVar('API_KEY', 'sk-abc123def456')];
      const content = generateExampleContent(vars);
      expect(content).toContain('# [SECRET]');
    });

    it('marks non-secret values with masked placeholder', () => {
      const vars = [makeVar('APP_NAME', 'my-application')];
      const content = generateExampleContent(vars);
      expect(content).toContain('APP_NAME=');
      // Non-secret values are still masked for safety
      expect(content).not.toContain('APP_NAME=my-application');
    });

    it('handles empty values', () => {
      const vars = [makeVar('EMPTY_VAR', '')];
      const content = generateExampleContent(vars);
      expect(content).toContain('EMPTY_VAR=');
    });

    it('includes all variables', () => {
      const vars = [
        makeVar('VAR_A', 'value-a'),
        makeVar('VAR_B', 'value-b'),
        makeVar('VAR_C', 'value-c'),
      ];
      const content = generateExampleContent(vars);
      expect(content).toContain('VAR_A=');
      expect(content).toContain('VAR_B=');
      expect(content).toContain('VAR_C=');
    });

    it('includes type hints from schema when provided', () => {
      const vars = [makeVar('PORT', '3000')];
      const schema = {
        PORT: {
          type: 'number',
          description: 'The server port',
          integer: true,
        },
      } as any;

      const content = generateExampleContent(vars, schema);
      expect(content).toContain('# type: number');
      expect(content).toContain('# The server port');
    });

    it('includes required marker when schema entry has no default', () => {
      const vars = [makeVar('REQUIRED_VAR', 'value')];
      const schema = {
        REQUIRED_VAR: {
          type: 'string',
        },
      } as any;

      const content = generateExampleContent(vars, schema);
      expect(content).toContain('# required');
    });

    it('includes optional marker when schema has default', () => {
      const vars = [makeVar('OPTIONAL_VAR', 'value')];
      const schema = {
        OPTIONAL_VAR: {
          type: 'string',
          default: 'default-value',
        },
      } as any;

      const content = generateExampleContent(vars, schema);
      expect(content).toContain('# optional');
      expect(content).toContain('# default: default-value');
    });

    it('redacts default value when it is a secret', () => {
      const vars = [makeVar('SECRET_VAR', 'secret-value')];
      const schema = {
        SECRET_VAR: {
          type: 'string',
          default: 'actual-secret',
          isSecret: true,
        },
      } as any;

      const content = generateExampleContent(vars, schema);
      expect(content).toContain('# default: [REDACTED]');
    });

    it('includes enum values from schema', () => {
      const vars = [makeVar('ENV', 'production')];
      const schema = {
        ENV: {
          type: 'enum',
          values: ['development', 'staging', 'production'],
        },
      } as any;

      const content = generateExampleContent(vars, schema);
      expect(content).toContain('# values: development, staging, production');
    });

    it('handles empty vars array', () => {
      const content = generateExampleContent([]);
      expect(content).toContain('Auto-generated by ultraenv');
      expect(content).toContain('Copy this file to .env');
    });

    it('respects includeDescriptions=false option', () => {
      const vars = [makeVar('PORT', '3000')];
      const schema = {
        PORT: {
          type: 'number',
          description: 'Server port',
        },
      } as any;

      const content = generateExampleContent(vars, schema, { includeDescriptions: false });
      expect(content).not.toContain('Server port');
    });

    it('respects includeTypes=false option', () => {
      const vars = [makeVar('PORT', '3000')];
      const schema = {
        PORT: {
          type: 'number',
        },
      } as any;

      const content = generateExampleContent(vars, schema, { includeTypes: false });
      expect(content).not.toContain('# type: number');
    });

    it('respects includeDefaults=false option', () => {
      const vars = [makeVar('PORT', '3000')];
      const schema = {
        PORT: {
          type: 'number',
          default: '8080',
        },
      } as any;

      const content = generateExampleContent(vars, schema, { includeDefaults: false });
      expect(content).not.toContain('# default:');
    });
  });

  // ===========================================================================
  // generateExampleFile
  // ===========================================================================
  describe('generateExampleFile', () => {
    it('reads the env file and writes the example file', async () => {
      mockReadFile.mockResolvedValueOnce('DATABASE_URL=postgres://localhost/db\n');
      mockParseEnvFile.mockReturnValueOnce({
        vars: [{
          key: 'DATABASE_URL',
          value: 'postgres://localhost/db',
          raw: 'postgres://localhost/db',
          source: '.env',
          lineNumber: 1,
          comment: '',
        }],
      });
      mockWriteFile.mockResolvedValueOnce(undefined);

      await generateExampleFile('.env', '.env.example');
      expect(mockReadFile).toHaveBeenCalledWith('.env');
      expect(mockWriteFile).toHaveBeenCalledWith('.env.example', expect.any(String));
    });

    it('writes content that includes the header', async () => {
      mockReadFile.mockResolvedValueOnce('KEY=value\n');
      mockParseEnvFile.mockReturnValueOnce({
        vars: [{
          key: 'KEY',
          value: 'value',
          raw: 'value',
          source: '.env',
          lineNumber: 1,
          comment: '',
        }],
      });
      mockWriteFile.mockResolvedValueOnce(undefined);

      await generateExampleFile('.env', '.env.example');
      const written = mockWriteFile.mock.calls[0]![1];
      expect(written).toContain('Auto-generated by ultraenv');
    });
  });

  // ===========================================================================
  // needsUpdate
  // ===========================================================================
  describe('needsUpdate', () => {
    it('returns true when env exists but example does not', async () => {
      mockExists.mockResolvedValueOnce(true);   // env exists
      mockExists.mockResolvedValueOnce(false);  // example doesn't
      const result = await needsUpdate('.env', '.env.example');
      expect(result).toBe(true);
    });

    it('returns false when neither exists', async () => {
      mockExists.mockResolvedValueOnce(false);  // env doesn't exist
      const result = await needsUpdate('.env', '.env.example');
      expect(result).toBe(false);
    });

    it('returns true when files differ', async () => {
      mockExists.mockResolvedValueOnce(true);
      mockExists.mockResolvedValueOnce(true);
      mockReadFile.mockResolvedValueOnce('KEY1=value1\n'); // env content
      mockReadFile.mockResolvedValueOnce('KEY2=value2\n'); // example content
      mockParseEnvFile.mockReturnValue({
        vars: [{
          key: 'KEY1',
          value: 'value1',
          raw: 'value1',
          source: '.env',
          lineNumber: 1,
          comment: '',
        }],
      });

      const result = await needsUpdate('.env', '.env.example');
      expect(result).toBe(true);
    });

    it('returns true when generated content differs from existing example', async () => {
      mockExists.mockResolvedValueOnce(true);
      mockExists.mockResolvedValueOnce(true);

      mockReadFile.mockResolvedValueOnce('KEY=value\n'); // env content
      mockReadFile.mockResolvedValueOnce('different-content\n'); // example content
      mockParseEnvFile.mockReturnValue({
        vars: [{
          key: 'KEY',
          value: 'value',
          raw: 'value',
          source: '.env',
          lineNumber: 1,
          comment: '',
        }],
      });

      const result = await needsUpdate('.env', '.env.example');
      expect(result).toBe(true);
    });
  });
});
