// =============================================================================
// ultraenv — TypeScript Declaration File Generator
// Generates a .d.ts file that augments NodeJS.ProcessEnv with typed env vars.
// =============================================================================

import type { SchemaDefinition } from '../core/types.js';
import { writeFile } from '../utils/fs.js';

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

export interface GenerateDeclarationOptions {
  /** Interface name for the generated env type (default: 'UltraenvEnv') */
  interfaceName?: string;
  /** Custom header comment */
  header?: string;
  /** Whether to include JSDoc comments from schema descriptions */
  jsdoc?: boolean;
  /** Indentation in spaces (default: 4) */
  indent?: number;
}

type SchemaEntry = SchemaDefinition[string];

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

const DEFAULT_HEADER = '// Auto-generated by ultraenv — DO NOT EDIT';

// -----------------------------------------------------------------------------
// Type Mapping
// -----------------------------------------------------------------------------

/**
 * Map a schema entry to its TypeScript representation for ProcessEnv.
 * All values are `string` in ProcessEnv, except enum types which use union literals.
 */
function schemaTypeToTsType(schema: SchemaEntry): string {
  const r = schema as unknown as Record<string, unknown>;
  const schemaType = r.type as string | undefined;

  if (schemaType === 'string' && Array.isArray(r.enum) && r.enum.length > 0) {
    return (r.enum as readonly string[]).map((v) => `'${v}'`).join(' | ');
  }

  if (schemaType === 'enum' && Array.isArray(r.values) && r.values.length > 0) {
    return (r.values as readonly string[]).map((v) => `'${v}'`).join(' | ');
  }

  return 'string';
}

// -----------------------------------------------------------------------------
// JSDoc Generation
// -----------------------------------------------------------------------------

function generateJSDoc(key: string, schema: SchemaEntry): string {
  const r = schema as unknown as Record<string, unknown>;
  const lines: string[] = ['/**'];

  if (schema.description !== undefined) {
    lines.push(` * ${schema.description}`);
  } else {
    lines.push(` * ${key}`);
  }

  if (r.isSecret === true) {
    lines.push(' * @secret');
  }

  const hasDefault = schema.default !== undefined || r.hasDefault === true;
  if (hasDefault) {
    const rawDefault = r.rawDefaultValue as string | undefined;
    const defaultVal = r.isSecret === true
      ? '[REDACTED]'
      : rawDefault ?? String(schema.default ?? '');
    lines.push(` * @default ${defaultVal}`);
  }

  if (r.isDeprecated === true) {
    const msg = r.deprecationMessage as string | undefined;
    lines.push(` * @deprecated ${msg ?? 'This variable is deprecated'}`);
  }

  lines.push(' */');
  return lines.join('\n');
}

// -----------------------------------------------------------------------------
// Public API
// -----------------------------------------------------------------------------

/**
 * Generate TypeScript declaration content that augments NodeJS.ProcessEnv.
 */
export async function generateDeclaration(
  vars: Record<string, string>,
  schema?: SchemaDefinition,
  outputPath?: string,
  options?: GenerateDeclarationOptions,
): Promise<string> {
  const content = generateDeclarationContent(vars, schema, options);

  if (outputPath !== undefined) {
    await writeFile(outputPath, content);
  }

  return content;
}

/**
 * Generate the TypeScript declaration file content string.
 */
export function generateDeclarationContent(
  vars: Record<string, string>,
  schema?: SchemaDefinition,
  options?: GenerateDeclarationOptions,
): string {
  const includeJSDoc = options?.jsdoc ?? true;
  const indent = options?.indent ?? 4;
  const indentStr = ' '.repeat(indent);
  const header = options?.header ?? DEFAULT_HEADER;

  const lines: string[] = [];

  lines.push(header);
  lines.push('');

  const allKeys = new Set<string>();
  for (const key of Object.keys(vars)) {
    allKeys.add(key);
  }
  if (schema !== undefined) {
    for (const key of Object.keys(schema)) {
      allKeys.add(key);
    }
  }

  const sortedKeys = Array.from(allKeys).sort();

  lines.push('declare namespace NodeJS {');
  lines.push(`${indentStr}interface ProcessEnv {`);

  for (const key of sortedKeys) {
    const schemaEntry = schema !== undefined ? schema[key] : undefined;

    if (includeJSDoc && schemaEntry !== undefined) {
      lines.push('');
      lines.push(`${indentStr}${indentStr}${generateJSDoc(key, schemaEntry)}`);
    }

    const tsType = schemaEntry !== undefined
      ? schemaTypeToTsType(schemaEntry)
      : 'string';

    const r = schemaEntry as unknown as Record<string, unknown> | undefined;
    const isOptional = schemaEntry === undefined
      || schemaEntry.optional === true
      || schemaEntry.default !== undefined
      || r?.hasDefault === true;

    const optionalMarker = isOptional ? '?' : '';
    lines.push(`${indentStr}${indentStr}${key}${optionalMarker}: ${tsType};`);
  }

  lines.push(`${indentStr}}`);
  lines.push('}');
  lines.push('');
  lines.push('export {};');

  return lines.join('\n');
}
