// =============================================================================
// ultraenv — Typed Module Generator
// Generates a TypeScript module with a strongly-typed Env interface
// that infers types from schema definitions.
// =============================================================================

import type { SchemaDefinition } from '../core/types.js';
import { writeFile } from '../utils/fs.js';

// -----------------------------------------------------------------------------
// Types
// -----------------------------------------------------------------------------

export interface GenerateModuleOptions {
  /** Interface name (default: 'Env') */
  interfaceName?: string;
  /** Custom header comment */
  header?: string;
  /** Whether to include JSDoc comments from schema descriptions */
  jsdoc?: boolean;
  /** Indentation in spaces (default: 2) */
  indent?: number;
  /** Whether to export the interface as default */
  exportAsDefault?: boolean;
}

type SchemaEntry = SchemaDefinition[string];

// -----------------------------------------------------------------------------
// Constants
// -----------------------------------------------------------------------------

const DEFAULT_HEADER = '// Auto-generated by ultraenv — DO NOT EDIT';

// -----------------------------------------------------------------------------
// Type Mapping (Schema → TypeScript)
// -----------------------------------------------------------------------------

/**
 * Map a schema entry to its proper TypeScript type.
 */
function schemaToTsType(schema: SchemaEntry): string {
  const r = schema as unknown as Record<string, unknown>;
  const schemaType = r.type as string | undefined;

  if (schemaType === 'string') {
    const enumValues = r.enum as readonly string[] | undefined;
    if (Array.isArray(enumValues) && enumValues.length > 0) {
      return enumValues.map((v) => `'${v}'`).join(' | ');
    }
    return 'string';
  }

  if (schemaType === 'number') return 'number';
  if (schemaType === 'boolean') return 'boolean';

  if (schemaType === 'enum') {
    const values = r.values as readonly string[] | undefined;
    if (Array.isArray(values) && values.length > 0) {
      return values.map((v) => `'${v}'`).join(' | ');
    }
    return 'string';
  }

  if (schemaType === 'array') return 'string[]';
  if (schemaType === 'json') return 'Record<string, unknown>';
  if (schemaType === 'date') return 'string';
  if (schemaType === 'bigint') return 'bigint';

  return 'string';
}

// -----------------------------------------------------------------------------
// JSDoc Generation
// -----------------------------------------------------------------------------

function generateModuleJSDoc(key: string, schema: SchemaEntry): string {
  const r = schema as unknown as Record<string, unknown>;
  const lines: string[] = ['/**'];

  if (schema.description !== undefined) {
    lines.push(` * ${schema.description}`);
  } else {
    lines.push(` * ${key}`);
  }

  if (r.isSecret === true) {
    lines.push(' * @secret This value should be kept confidential');
  }

  const hasDefault = schema.default !== undefined || r.hasDefault === true;
  if (hasDefault) {
    const rawDefault = r.rawDefaultValue as string | undefined;
    const defaultDisplay =
      r.isSecret === true ? '[REDACTED]' : (rawDefault ?? String(schema.default ?? ''));
    lines.push(` * @default ${defaultDisplay}`);
  }

  if (r.isDeprecated === true) {
    const msg = r.deprecationMessage as string | undefined;
    lines.push(` * @deprecated ${msg ?? 'This variable is deprecated'}`);
  }

  if (r.type === 'enum') {
    const values = r.values as readonly string[] | undefined;
    if (Array.isArray(values) && values.length > 0) {
      lines.push(` * @enum {${values.map((v) => `'${v}'`).join('|')}}`);
    }
  }

  lines.push(' */');
  return lines.join('\n');
}

// -----------------------------------------------------------------------------
// Field Optionality
// -----------------------------------------------------------------------------

function isOptionalField(schema: SchemaEntry): boolean {
  const r = schema as unknown as Record<string, unknown>;

  if (schema.optional === true) {
    return true;
  }

  if (schema.default !== undefined) {
    return false;
  }

  if (r.hasDefault === true) {
    return false;
  }

  return false;
}

// -----------------------------------------------------------------------------
// Public API
// -----------------------------------------------------------------------------

/**
 * Generate a TypeScript module with a typed Env interface.
 */
export async function generateModule(
  schema: SchemaDefinition,
  outputPath?: string,
  options?: GenerateModuleOptions,
): Promise<string> {
  const content = generateModuleContent(schema, options);

  if (outputPath !== undefined) {
    await writeFile(outputPath, content);
  }

  return content;
}

/**
 * Generate the TypeScript module content string.
 */
export function generateModuleContent(
  schema: SchemaDefinition,
  options?: GenerateModuleOptions,
): string {
  const includeJSDoc = options?.jsdoc ?? true;
  const indent = options?.indent ?? 2;
  const indentStr = ' '.repeat(indent);
  const header = options?.header ?? DEFAULT_HEADER;
  const interfaceName = options?.interfaceName ?? 'Env';
  const exportAsDefault = options?.exportAsDefault ?? false;

  const lines: string[] = [];

  lines.push(header);
  lines.push('');

  if (exportAsDefault) {
    lines.push('export default interface Env {');
  } else {
    lines.push(`export interface ${interfaceName} {`);
  }

  const sortedKeys = Object.keys(schema).sort();

  for (const key of sortedKeys) {
    const schemaEntry = schema[key];
    if (schemaEntry === undefined) continue;

    if (includeJSDoc) {
      lines.push('');
      lines.push(`${indentStr}${generateModuleJSDoc(key, schemaEntry)}`);
    }

    const tsType = schemaToTsType(schemaEntry);
    const optional = isOptionalField(schemaEntry);

    const optionalMarker = optional ? '?: ' : ': ';
    lines.push(`${indentStr}${key}${optionalMarker}${tsType};`);
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
