// =============================================================================
// ultraenv — CLI Command: init
// Interactive project initialization.
// =============================================================================

import type { ParsedArgs } from '../parser.js';
import type { CommandContext } from './types.js';
import { prompt, confirm } from '../ui/prompt.js';
import { writeLine, writeError } from '../ui/renderer.js';
import { green, red, cyan, bold } from '../ui/colors.js';
import { writeFile, exists } from '../../utils/fs.js';
import { resolve, join } from 'node:path';
import { DEFAULT_GITIGNORE_ENTRIES } from '../../core/constants.js';
import { getErrorMessage, FileSystemError } from '../../core/errors.js';

const DEFAULT_ENV_CONTENT = `# Environment Variables
# Created by ultraenv — https://github.com/Avinashvelu03/ultraenv

# App
NODE_ENV=development
APP_NAME=
APP_URL=http://localhost:3000

# Database
DATABASE_URL=
DATABASE_POOL_SIZE=10

# Server
PORT=3000
HOST=localhost

# Logging
LOG_LEVEL=info
`;

export async function run(args: ParsedArgs, ctx: CommandContext): Promise<number> {
  try {
    const cwd = (args.flags['--cwd'] as string) ?? ctx.cwd;
    const baseDir = resolve(cwd);

    writeLine(bold('🚀 ultraenv project initialization'));
    writeLine('');

    // Check if already initialized
    const configPath = join(baseDir, '.ultraenvrc.json');
    const envPath = join(baseDir, '.env');

    if ((await exists(configPath)) && !args.flags['--force']) {
      writeLine(cyan('  An ultraenv configuration already exists.'));
      const overwrite = await confirm('  Overwrite existing configuration?', false);
      if (!overwrite) {
        writeLine(green('  Initialization cancelled.'));
        return 0;
      }
    }

    // Interactive prompts
    await prompt('  Project name', { default: baseDir.split('/').pop() ?? 'my-project' });
    const envDir = await prompt('  Environment directory', { default: '.' });

    writeLine('');

    // Create config file
    writeLine(cyan('  Creating configuration...'));
    const configContent =
      JSON.stringify(
        {
          envDir,
          expandVariables: true,
          overrideProcessEnv: false,
          mergeStrategy: 'last-wins',
          outputFormat: 'terminal',
          debug: false,
        },
        null,
        2,
      ) + '\n';
    await writeFile(configPath, configContent);
    writeLine(green(`  ✓ Created ${configPath}`));

    // Create .env file
    if (!(await exists(envPath))) {
      writeLine(cyan('  Creating .env file...'));
      await writeFile(envPath, DEFAULT_ENV_CONTENT);
      writeLine(green(`  ✓ Created ${envPath}`));
    } else {
      writeLine(cyan(`  .env already exists, skipping.`));
    }

    // Create .env.example
    const examplePath = join(baseDir, '.env.example');
    if (!(await exists(examplePath))) {
      const exampleContent = `# Environment Variables Template
# Auto-generated by ultraenv
# Copy this file to .env and fill in the values

# App
NODE_ENV=development
APP_NAME=<your-app-name>
APP_URL=http://localhost:3000

# Database
DATABASE_URL=<your-database-url>
DATABASE_POOL_SIZE=10

# Server
PORT=3000
HOST=localhost

# Logging
LOG_LEVEL=info
`;
      await writeFile(examplePath, exampleContent);
      writeLine(green(`  ✓ Created ${examplePath}`));
    }

    // Update .gitignore
    const gitignorePath = join(baseDir, '.gitignore');
    if (await exists(gitignorePath)) {
      const { readFile } = await import('../../utils/fs.js');
      const existingContent = await readFile(gitignorePath);
      if (!existingContent.includes('# ultraenv')) {
        const { appendFileSync } = await import('node:fs');
        appendFileSync(gitignorePath, '\n' + DEFAULT_GITIGNORE_ENTRIES.join('\n') + '\n');
        writeLine(green('  ✓ Updated .gitignore'));
      } else {
        writeLine(cyan('  .gitignore already contains ultraenv entries'));
      }
    } else {
      const gitignoreContent = DEFAULT_GITIGNORE_ENTRIES.join('\n') + '\n';
      await writeFile(gitignorePath, gitignoreContent);
      writeLine(green('  ✓ Created .gitignore'));
    }

    writeLine('');
    writeLine(green(bold('  ✅ ultraenv initialized successfully!')));
    writeLine('');
    writeLine(cyan('  Next steps:'));
    writeLine(`    1. Edit ${envPath} with your environment variables`);
    writeLine(`    2. Edit ${configPath} to customize settings`);
    writeLine(`    3. Run ${cyan('ultraenv validate')} to check your configuration`);
    writeLine('');

    return 0;
  } catch (error: unknown) {
    if (error instanceof FileSystemError) {
      writeError(red(`  Error: ${getErrorMessage(error)}`));
      return 1;
    }
    writeError(red(`  Error: ${error instanceof Error ? error.message : String(error)}`));
    return 1;
  }
}
